name: Deploy to playground dev S3 on dev push

on:
  push:
    branches:
      - playground_dev
  workflow_dispatch: 
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # ✅ Required for OIDC
      contents: read     # ✅ Required for checkout
      
    environment: playground-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd frontend && npm install --legacy-peer-deps

      - name: Build project
        run: cd frontend && npm run build
        env:
          VITE_BASE_URL_PROD: ${{ secrets.VITE_BASE_URL_PROD }}
          VITE_PROJECT_KEY: ${{ secrets.VITE_PROJECT_KEY }}
          VITE_API_STAGE: ${{ secrets.VITE_API_STAGE }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_PDF_CONVERTER_URL: ${{ secrets.VITE_PDF_CONVERTER_URL }}
          VITE_USE_EXTERNAL_PDF_CONVERTER: ${{ secrets.VITE_USE_EXTERNAL_PDF_CONVERTER }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Deploy to S3
        run: |
          aws s3 sync frontend/dist/ s3://${{ secrets.S3_BUCKET_NAME }}/ --delete